INSERT INTO chameleon.stop (id, power, name, task, task_description, task_solution) VALUES (1, 2, 'Vsetínská', 1, '', '');
INSERT INTO chameleon.stop (id, power, name, task, task_description, task_solution) VALUES (2, 2, 'Zvonařka', 0, '', '');
INSERT INTO chameleon.stop (id, power, name, task, task_description, task_solution) VALUES (3, 2, 'Celní', 0, '', '');
INSERT INTO chameleon.stop (id, power, name, task, task_description, task_solution) VALUES (4, 4, 'Křídlovická', 1, '', '');
INSERT INTO chameleon.stop (id, power, name, task, task_description, task_solution) VALUES (5, 4, 'Poříčí', 0, '', '');
INSERT INTO chameleon.stop (id, power, name, task, task_description, task_solution) VALUES (6, 3, 'Pisárky', 0, '', '');
INSERT INTO chameleon.stop (id, power, name, task, task_description, task_solution) VALUES (7, 6, 'Mendlovo náměstí', 1, '', '');
INSERT INTO chameleon.stop (id, power, name, task, task_description, task_solution) VALUES (8, 8, 'Hlavní nádraží', 0, '', '');
INSERT INTO chameleon.stop (id, power, name, task, task_description, task_solution) VALUES (9, 4, 'Körnerova', 1, '', '');
INSERT INTO chameleon.stop (id, power, name, task, task_description, task_solution) VALUES (10, 2, 'Nemocnice u Sv. Anny', 1, '', '');
INSERT INTO chameleon.stop (id, power, name, task, task_description, task_solution) VALUES (11, 4, 'Šilingrovo náměstí', 0, '', '');
INSERT INTO chameleon.stop (id, power, name, task, task_description, task_solution) VALUES (12, 2, 'Náměstí svobody', 1, '', '');
INSERT INTO chameleon.stop (id, power, name, task, task_description, task_solution) VALUES (13, 3, 'Vojenská nemocnice', 0, '', '');
INSERT INTO chameleon.stop (id, power, name, task, task_description, task_solution) VALUES (14, 3, 'Stará osada', 1, '', '');
INSERT INTO chameleon.stop (id, power, name, task, task_description, task_solution) VALUES (15, 2, 'Trávníčkova', 0, '', '');
INSERT INTO chameleon.stop (id, power, name, task, task_description, task_solution) VALUES (16, 3, 'Židenice nádraží', 0, '', '');
INSERT INTO chameleon.stop (id, power, name, task, task_description, task_solution) VALUES (17, 5, 'Česká', 0, '', '');
INSERT INTO chameleon.stop (id, power, name, task, task_description, task_solution) VALUES (18, 4, 'Moravské náměstí', 0, '', '');
INSERT INTO chameleon.stop (id, power, name, task, task_description, task_solution) VALUES (19, 3, 'Náměstí 28. října', 0, '', '');
INSERT INTO chameleon.stop (id, power, name, task, task_description, task_solution) VALUES (20, 5, 'Jugoslávská', 1, '', '');
INSERT INTO chameleon.stop (id, power, name, task, task_description, task_solution) VALUES (21, 2, 'Vozovna Husovice', 1, '', '');
INSERT INTO chameleon.stop (id, power, name, task, task_description, task_solution) VALUES (22, 3, 'Úvoz', 0, '', '');
INSERT INTO chameleon.stop (id, power, name, task, task_description, task_solution) VALUES (23, 3, 'Tomkovo náměstí', 0, '', '');
INSERT INTO chameleon.stop (id, power, name, task, task_description, task_solution) VALUES (24, 5, 'Konečného náměstí', 1, '', '');
INSERT INTO chameleon.stop (id, power, name, task, task_description, task_solution) VALUES (25, 5, 'Sušilova', 0, '', '');
INSERT INTO chameleon.stop (id, power, name, task, task_description, task_solution) VALUES (26, 5, 'Pionýrská', 1, '', '');
INSERT INTO chameleon.stop (id, power, name, task, task_description, task_solution) VALUES (27, 4, 'Zimní stadion', 0, '', '');
INSERT INTO chameleon.stop (id, power, name, task, task_description, task_solution) VALUES (28, 4, 'Lesnická', 1, '', '');
INSERT INTO chameleon.stop (id, power, name, task, task_description, task_solution) VALUES (29, 3, 'Merhautova', 0, '', '');
INSERT INTO chameleon.stop (id, power, name, task, task_description, task_solution) VALUES (30, 3, 'Tábor', 1, '', '');
INSERT INTO chameleon.stop (id, power, name, task, task_description, task_solution) VALUES (31, 6, 'Klusáčkova', 0, '', '');
INSERT INTO chameleon.stop (id, power, name, task, task_description, task_solution) VALUES (32, 3, 'Šelepova', 1, '', '');
INSERT INTO chameleon.stop (id, power, name, task, task_description, task_solution) VALUES (33, 3, 'Štefánikova čtvrť', 1, '', '');
INSERT INTO chameleon.stop (id, power, name, task, task_description, task_solution) VALUES (34, 3, 'Mozolky', 0, '', '');
INSERT INTO chameleon.stop (id, power, name, task, task_description, task_solution) VALUES (35, 2, 'Reisigova', 0, '', '');
INSERT INTO chameleon.stop (id, power, name, task, task_description, task_solution) VALUES (36, 3, 'Vozovna Komín', 1, '', '');
INSERT INTO chameleon.stop (id, power, name, task, task_description, task_solution) VALUES (37, 2, 'Dobrovského', 0, '', '');
INSERT INTO chameleon.stop (id, power, name, task, task_description, task_solution) VALUES (38, 3, 'Kartouzská', 0, '', '');
INSERT INTO chameleon.stop (id, power, name, task, task_description, task_solution) VALUES (39, 2, 'Královopolská strojírna', 1, '', '');
INSERT INTO chameleon.stop (id, power, name, task, task_description, task_solution) VALUES (40, 3, 'Halasovo náměstí', 0, '', '');
INSERT INTO chameleon.stop (id, power, name, task, task_description, task_solution) VALUES (41, 4, 'Lesná nádraží', 1, '', '');
INSERT INTO chameleon.stop (id, power, name, task, task_description, task_solution) VALUES (42, 3, 'Přívrat', 0, '', '');
INSERT INTO chameleon.stop (id, power, name, task, task_description, task_solution) VALUES (43, 3, 'Skácelova', 1, '', '');
INSERT INTO chameleon.stop (id, power, name, task, task_description, task_solution) VALUES (44, 4, 'Slovanské náměstí', 0, '', '');
INSERT INTO chameleon.stop (id, power, name, task, task_description, task_solution) VALUES (45, 3, 'Semilasso', 1, '', '');
INSERT INTO chameleon.stop (id, power, name, task, task_description, task_solution) VALUES (46, 3, 'Královo pole nádraží', 0, '', '');
INSERT INTO chameleon.stop (id, power, name, task, task_description, task_solution) VALUES (47, 3, 'Náměstí svornosti', 1, '', '');
INSERT INTO chameleon.stop (id, power, name, task, task_description, task_solution) VALUES (48, 3, 'Štefánikova', 0, '', '');
INSERT INTO chameleon.stop (id, power, name, task, task_description, task_solution) VALUES (49, 4, 'Hybešova', 0, '', '');
INSERT INTO chameleon.stop (id, power, name, task, task_description, task_solution) VALUES (50, 2, 'Velodrom', 0, '', '');
INSERT INTO chameleon.stop (id, power, name, task, task_description, task_solution) VALUES (51, 3, 'Malinovského náměstí', 0, '', '');
